apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: f74gyc8qe-java-quarkus
  janus-idp.io/tekton: f74gyc8qe-java-quarkus
  backstage.io/kubernetes-id: f74gyc8qe-java-quarkus
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: f74gyc8qe-java-quarkus
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
